### ISSUE TITLE
Failed to load the clickable-npm-scripts package

### ISSUE THREAD

**Issue by Austinthemighty** [bhargav175/clickable-npm-scripts#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.2 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Home
**Thrown From**: [clickable-npm-scripts](https://github.com/bhargav175/clickable-npm-scripts) package 3.5.5

### Stack Trace

Failed to load the clickable-npm-scripts package

```
At Cannot find module 'debug'

Error: Cannot find module 'debug'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.14.2/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/clickable-npm-scripts/lib/clickable-npm-scripts-view.js:3:31)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/clickable-npm-scripts/lib/clickable-npm-scripts.js:7:32)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at /app.asar/src/package.js:123:28
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at Package.module.exports.Package.load (/app.asar/src/package.js:110:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/app.asar/src/package-manager.js:468:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:548:30)
    at /app.asar/node_modules/settings-view/lib/package-manager.js:439:29
    at exit (/app.asar/node_modules/settings-view/lib/package-manager.js:69:16)
    at triggerExitCallback (/app.asar/src/buffered-process.js:303:11)
    at /app.asar/src/buffered-process.js:333:11)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
  2x -9:23.5.0 script:run (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 1.2.0 
atom-python-run 0.7.3 
atomic-chrome 0.3.0 
autocomplete-python 1.8.54 
clickable-npm-scripts 3.5.5 
css-color-underline 1.0.1 
emmet 2.4.3 
file-icons 2.0.15 
git-plus 7.3.0 
lint 0.0.1 
linter 1.11.23 
linter-csslint 1.3.3 
linter-javac 1.9.4 
linter-php 1.3.1 
linter-pylint 1.2.2 
open-github-from-npm 0.1.1 
project-manager 3.3.3 
qolor 0.4.1 
script 3.14.1 
```

**Comment by imbhargav5** [comment]
@Austinthemighty Just published a patch. Please try and let me know.

**Comment by imbhargav5** [comment]
Fixed in the latest version.
